name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Compile ip_check
      run: |
        gcc -Wall -Werror -Wextra -stc=c11 -c ./src/ip_lib.c -o ./src/ip_lib.o
        gcc -Wall -Werror -Wextra -stc=c11 ./src/ip_check.c ./src/ip_lib.o -o ./src/ip_check
    
    - name: Compile mask_check if exists
      if: ${{ hashFiles('./src/mask_check.c') != '' }}
      run: |
        gcc -Wall -Werror -Wextra -stc=c11 -c ./src/ip_lib.c -o ./src/ip_lib.o
        gcc -Wall -Werror -Wextra -stc=c11 ./src/mask_check.c ./src/ip_lib.o -o ./src/mask_check
        
    - name: Build project using make
      run: |
        chmod +x ./make.sh
        ./make.sh

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run Pytest
      run: |
        pytest --color=yes -v --tb=short --html=pytest_report.html tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest_report.html

    - name: Set up clang-format
      run: |
        sudo apt-get install -y clang-format

    - name: Check code style with clang-format
      run: |
        cp clang/.clang-format .
        if clang-format -n --Werror $(find src/ -name '*.c' -o -name '*.h'); then
          echo "clang-format check passed"
        else
          echo "clang-format check failed. Hey, frogger, use clang-format to fix the style issues."
          exit 1
        fi

    - name: Set up cppcheck
      run: |
        sudo apt install cppcheck

    - name: Check code with cppcheck
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 $(find src/ -name '*.c' -o -name '*.h')
